# Generated by Django 5.2.8 on 2026-01-01 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_cliente_ciudad_cliente_notas_cliente_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripción', models.TextField()),
                ('tipo_evento', models.CharField(choices=[('concierto', 'Concierto'), ('show', 'Show'), ('streaming', 'Streaming'), ('fiesta', 'Fiesta'), ('sesion_fotografica', 'Sesión Fotográfica'), ('otro', 'Otro')], default='otro', max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('presupuesto_estimado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('propuesta', 'Propuesta'), ('aprobado', 'Aprobado'), ('en_proceso', 'En Proceso'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='propuesta', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='clientes.cliente')),
            ],
        ),
    ]
