# Generated by Django 5.2.8 on 2026-06-06 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='descripción',
            new_name='descripcion',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_asignados', to=settings.AUTH_USER_MODEL),
        ),
    ]
