# Generated by Django 5.2.8 on 2026-06-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigSMTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_usuario', models.EmailField(help_text='Correo desde el que se enviarán los mensajes', max_length=150)),
                ('email_password', models.CharField(help_text='Contraseña o Token de aplicación', max_length=255)),
                ('servidor_host', models.CharField(default='smtp.gmail.com', max_length=100)),
                ('puerto', models.IntegerField(default=587)),
                ('use_tls', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlantillaMensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('email', 'Correo Electrónico (SMTP)'), ('whatsapp', 'WhatsApp URL')], max_length=20)),
                ('asunto', models.CharField(blank=True, max_length=200, null=True)),
                ('contenido', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
