# Generated by Django 5.2.8 on 2026-10-05 18:04

from django.db import migrations, models


def clear_legacy_smtp_passwords(apps, schema_editor):
    ConfigSMTP = apps.get_model("marketing", "ConfigSMTP")
    ConfigSMTP.objects.exclude(email_password="").update(email_password="")


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_objetivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configsmtp',
            name='email_password',
            field=models.CharField(blank=True, default='', help_text='Se conserva vacío; el secreto se carga desde CRM_SMTP_PASSWORD.', max_length=255),
        ),
        migrations.RunPython(clear_legacy_smtp_passwords, migrations.RunPython.noop),
    ]
