# Generated by Django 5.2.8 on 2026-06-07 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interacciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interaccion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interaccion',
            name='tipo',
            field=models.CharField(choices=[('llamada', 'Llamada'), ('correo_manual', 'Correo Manual'), ('reunión', 'Reunión'), ('seguimiento', 'Seguimiento'), ('email_marketing', 'Campaña de Email (Automatizada)'), ('whatsapp_link', 'Enlace de WhatsApp Generado')], max_length=50),
        ),
    ]
