# Generated by Django 5.2.8 on 2026-06-08 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_ciudad_cliente_notas_cliente_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='origen',
            field=models.CharField(choices=[('web', 'Sitio Web'), ('whatsapp', 'WhatsApp Directo'), ('redes', 'Redes Sociales'), ('referido', 'Referido'), ('otro', 'Otro')], default='otro', max_length=50),
        ),
    ]
